trigger:
 - main
pool: 
  vmImage: 'ubuntu-latest'

steps:
# log in to registry
- task: Docker@2
  inputs:
    containerRegistry: '<your-container-registry-service-connection>'
    command: 'login'
    
# build and push artifact to registry
- task: Docker@2
  inputs:
    repository: '<name-of-your-repository>'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'
# install notation
- task: Notation@0
  inputs:
    command: 'install'
    version: '1.3.2'
# automatically detect the artifact pushed by Docker task and sign the artifact.
- task: Notation@0
  inputs:
    command: 'sign'
    plugin: 'azureKeyVault'
    akvPluginVersion: '1.2.1'
    azurekvServiceConection: '<name-of-your-Azure-Resource-Manager-service-connection>'
    keyid: 'https://<certficate-name>.vault.azure.net/keys/<key-name>/<key-version>'
    selfSigned: true
# verify the signature of the artifact using the trust policy file and trust store.
- task: Notation@0
  inputs:
    command: 'verify'
    trustPolicy: 'trustpolicy-selfsigned-akv.template.json'
    trustStore: './assets/notation'